### ISSUE TITLE
Eliminar archivos que no deben incluirse en un control de versiones

### ISSUE THREAD

**Issue by jesustorresdev** [samjxxxx/UnityTFG#1]
GitHub mantiene una archivo .gitignore que señala archivos y carpetas que no deben incluirse en el repositorio:

https://github.com/github/gitignore/blob/master/Unity.gitignore

sería buena idea incluirlo en el proyecto y eliminar los archivos que cumplen con esas reglas. El motivo es que esos archivos no son "código fuente". Se regeneran al abrir el proyecto así que no hace falta meterlos en el repo.

**Comment by JiaqiJin** [comment]
Lo incluiré en el proyecto gracias profesor2020年2月2日 下午8:53，Jesús Torres <notifications@github.com>写道：GitHub mantiene una archivo .gitignore que señala archivos y carpetas que no deben incluirse en el repositorio:

https://github.com/github/gitignore/blob/master/Unity.gitignore

sería buena idea incluirlo en el proyecto y eliminar los archivos que cumplen con esas reglas. El motivo es que esos archivos no son "código fuente". Se regeneran al abrir el proyecto así que no hace falta meterlos en el repo.

**Comment by JiaqiJin** [comment]
Una vez subido los archivos como puedo ignorar los archivos del github?

**Comment by jesustorresdev** [comment]
Añade al repositorio el archivo .gitignore que te dije.

**Comment by samjxxxx** [comment]
ya lo subí pero los archivos no se han eliminado.

**Comment by samjxxxx** [comment]
Lo busque dice que hay que eliminar los archivos del github o creo otro repositiorio nuevo?

**Comment by jesustorresdev** [comment]
Ok. No te había entendido. Sigue uno de estos consejos:

https://stackoverflow.com/questions/13541615/how-to-remove-files-that-are-listed-in-the-gitignore-but-still-on-the-repositor

**Comment by JiaqiJin** [comment]
Gracias profesor , como uso Windows tuve que descargar el git Shell para manejarme con el comando.

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Jesús Torres<mailto:notifications@github.com>
Enviado: miércoles, 5 de febrero de 2020 21:55
Para: samjxxxx/UnityTFG<mailto:UnityTFG@noreply.github.com>
CC: JiaqiJin<mailto:fdsam@hotmail.com>; Comment<mailto:comment@noreply.github.com>
Asunto: Re: [samjxxxx/UnityTFG] Eliminar archivos que no deben incluirse en un control de versiones (#1)


Ok. No te había entendido. Sigue uno de estos consejos:

https://stackoverflow.com/questions/13541615/how-to-remove-files-that-are-listed-in-the-gitignore-but-still-on-the-repositor
